name: Build & Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: make all

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: tests
        run: make test
