name: Build & Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libx11-dev

    - name: build
      run: make build

  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libx11-dev

      - name: tests
        run: make test
